ai.api.url=https://integrate.api.nvidia.com/v1/chat/completions
ai.api.key=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
ai.model=nvidia/nemotron-3-super-120b-a12b
# OPTIONAL: server
server.port=8080